# Site settings
title: SEKE
email: devbyseke@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Games developed by SEKE.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  jeonse3875

# Build settings
markdown: kramdown
host: 0.0.0.0
port: 4000

